// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "sparklin": {
      name: "sparklin",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/global/sparklin.tsx"],
      component: React.lazy(() => import("@/registry/default/global/sparklin.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "form-generator": {
      name: "form-generator",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/global/form-generator.tsx"],
      component: React.lazy(() => import("@/registry/default/global/form-generator.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "glass-card": {
      name: "glass-card",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/global/glass-card.tsx"],
      component: React.lazy(() => import("@/registry/default/global/glass-card.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "gradient-background": {
      name: "gradient-background",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/global/gradient-background.tsx"],
      component: React.lazy(() => import("@/registry/default/global/gradient-background.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-border": {
      name: "animated-border",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/global/animated-border.tsx"],
      component: React.lazy(() => import("@/registry/default/global/animated-border.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sparklin-demo": {
      name: "sparklin-demo",
      type: "registry:example",
      registryDependencies: ["spaklin"],
      files: ["registry/default/example/sparklin-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/sparklin-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "form-generator-demo": {
      name: "form-generator-demo",
      type: "registry:example",
      registryDependencies: ["form-generator","glass-card"],
      files: ["registry/default/example/form-generator-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/form-generator-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "gradient-background-demo": {
      name: "gradient-background-demo",
      type: "registry:example",
      registryDependencies: ["gradient-background"],
      files: ["registry/default/example/gradient-background-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/gradient-background-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "animated-border-demo": {
      name: "animated-border-demo",
      type: "registry:example",
      registryDependencies: ["animated-border"],
      files: ["registry/default/example/animated-border-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/animated-border-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
